import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavbarMenu } from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="flex item-center justify-center p-4">
          <div className="border rounded-lg">          
            <NavbarMenu/>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
